title: LEE YatMing Liam
logo: /assets/CV.jpg
description: It is the project using Sentiment Analysis and Emotion Analysis with the Kaggle dataset.
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: false
